
from __future__ import annotations

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, UUID4
from decimal import Decimal
from datetime import datetime, date
from app.models.title import CategoryType
from app.schemas.venue import VenueSummary 

# Title Image
class TitleImageBase(BaseModel):
    image_url: str
    display_order: int = 0
    caption: Optional[str] = None


class TitleImageCreate(TitleImageBase):
    pass


class TitleImage(TitleImageBase):
    id: UUID4
    title_id: UUID4

    class Config:
        from_attributes = True


# Title — Create (admin POST /admin/titles)
# slug is auto-generated by backend, not provided by client
class TitleCreate(BaseModel):
    category: CategoryType
    title: str
    description: Optional[str] = None
    short_description: Optional[str] = None
    image_url: Optional[str] = None
    duration_minutes: Optional[int] = None
    tags: Optional[List[str]] = None
    meta: Optional[Dict[str, Any]] = None
    is_featured: bool = False


# Title — Update (admin PATCH /admin/titles/{id})
class TitleUpdate(BaseModel):
    title: Optional[str] = None
    category: Optional[CategoryType] = None
    description: Optional[str] = None
    short_description: Optional[str] = None
    image_url: Optional[str] = None
    duration_minutes: Optional[int] = None
    tags: Optional[List[str]] = None
    meta: Optional[Dict[str, Any]] = None
    is_featured: Optional[bool] = None


# Title — Full response (GET /titles/{slug})
class Title(BaseModel):
    id: UUID4
    category: CategoryType
    title: str
    slug: str
    description: Optional[str] = None
    short_description: Optional[str] = None
    image_url: Optional[str] = None
    duration_minutes: Optional[int] = None
    tags: Optional[List[str]] = None
    meta: Optional[Dict[str, Any]] = None
    rating: Decimal
    rating_count: int
    is_featured: bool
    is_active: bool
    created_at: datetime
    updated_at: Optional[datetime] = None
    images: List[TitleImage] = []

    class Config:
        from_attributes = True


# Title — Browse card (GET /titles list items, Screen 4)
# Includes computed fields for the browse grid
class TitleBrowseCard(BaseModel):
    id: UUID4
    category: CategoryType
    title: str
    slug: str
    short_description: Optional[str] = None
    image_url: Optional[str] = None
    duration_minutes: Optional[int] = None
    rating: Decimal
    rating_count: int
    is_featured: bool
    tags: Optional[List[str]] = None
    meta: Optional[Dict[str, Any]] = None
    min_price: Optional[Decimal] = None
    venue_count: int = 0
    cities: List[str] = []

    class Config:
        from_attributes = True


# --- Listing schemas ---


# Inline time slot for listing creation
class TimeSlotInline(BaseModel):
    hall_id: UUID4
    slot_date: date
    start_time: str  # "HH:MM" or "HH:MM:SS"
    end_time: str
    capacity: int
    price_override: Optional[Decimal] = None


# Listing — Create (admin POST /admin/titles/{id}/listings)
class ListingCreate(BaseModel):
    venue_id: UUID4
    price: Optional[Decimal] = None
    currency: str = "INR"
    start_datetime: Optional[datetime] = None
    end_datetime: Optional[datetime] = None
    total_capacity: Optional[int] = None
    time_slots: Optional[List[TimeSlotInline]] = None


# Listing — Update (admin PATCH /admin/listings/{id})
class ListingUpdate(BaseModel):
    price: Optional[Decimal] = None
    currency: Optional[str] = None
    start_datetime: Optional[datetime] = None
    end_datetime: Optional[datetime] = None
    total_capacity: Optional[int] = None
    status: Optional[str] = None


# Listing — DB response
class Listing(BaseModel):
    id: UUID4
    title_id: UUID4
    venue_id: Optional[UUID4] = None
    city: Optional[str] = None
    price: Optional[Decimal] = None
    currency: str = "INR"
    start_datetime: Optional[datetime] = None
    end_datetime: Optional[datetime] = None
    total_capacity: Optional[int] = None
    booked_count: int = 0
    status: str = "active"
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# Listing with nested venue — used in title detail response (Screen 5)
class ListingWithVenue(Listing):
    venue: Optional[VenueSummary] = None

    class Config:
        from_attributes = True


# Title detail — full page response (GET /titles/{slug}, Screen 5)
class TitleDetail(Title):
    listings: List[ListingWithVenue] = []


# Compact listing info for booking responses
class ListingSummary(BaseModel):
    title: str
    image_url: Optional[str] = None
    category: Optional[CategoryType] = None

    class Config:
        from_attributes = True


ListingWithVenue.model_rebuild()
TitleDetail.model_rebuild()
